name: Java CI Build SDK with Gradle

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Restore gradle.properties
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        echo "github_maven_user=${GITHUB_USER}" > gradle.properties
        echo "github_maven_password=${GITHUB_TOKEN}" >> gradle.properties
    - name: Build with Gradle
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      shell: bash
      run: |
        git config user.email "$GITHUB_USER@users.noreply.github.com"
        git config user.name  "$GITHUB_USER"
        git remote update
        git pull
        cd tools/sdk
        pwd
        gradle cV
      

