name: Java CI with Gradle

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Restore gradle.properties and Build with Gradle
      env:
        GITHUB_USER: arhacc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        git remote update
#        cd tools/sdk
#        ./gradlew wrapper
        echo "github_maven_user=${GITHUB_USER}" > gradle.properties
        echo "github_maven_password=${GITHUB_TOKEN}" >> gradle.properties
#        ./gradlew build
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

